// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

import {Test} from "forge-std/Test.sol";
import {Auction} from "src/Auction.sol";
import {HelperConfig} from "script/HelperConfig.s.sol";
import {MockERC721} from "test/mock/MockERC721.sol";

/// @title AuctionFuzzTest
/// @notice Fuzz tests for the Auction contract (start + bid paths).
/// @dev
/// - Uses Foundry fuzzing to test many randomized inputs.
/// - Uses `vm.assume` to constrain the fuzz space to meaningful addresses/values.
/// - Uses `bound` to keep bid values within valid ranges.
/// - Uses `vm.warp` to simulate time passing for expiry-related conditions.
contract AuctionFuzzTest is Test {
    Auction public auction;
    MockERC721 public nft;
    HelperConfig public config;

    uint256 public tokenId;
    address public seller;

    // -----------------------------
    // Constants / test configuration
    // -----------------------------
    uint256 public constant INITAL_BALANCE = 100 ether; // NOTE: declared but not used in this file
    uint256 public constant MAX_UINT_128 = type(uint128).max;

    address public constant ADDRESS_ZERO = address(0);
    uint256 public constant ZERO = 0;

    // Auction status values (mirrors Auction.Status enum cast to uint)
    uint256 public constant STATUS_NOT_STARTED = 0;
    uint256 public constant STATUS_START = 1;
    uint256 public constant STATUS_END = 2;

    /// @dev Deterministic test address generated by Foundry.
    address public bob = makeAddr("bob");

    /// @notice Helper modifier to ensure the auction is started before running a test.
    /// @dev
    /// - Uses `vm.prank(seller)` to impersonate the seller.
    /// - Assumes `tokenId` has been minted to the seller and approved to the auction contract.
    modifier startAuction() {
        vm.prank(seller);
        auction.start(address(nft), tokenId);
        _;
    }

    /// @notice Sets up fresh state before each test.
    /// @dev
    /// - Deploys Auction + MockERC721 via HelperConfig.
    /// - Pulls the seller from the Auction contract (immutable set at deployment).
    /// - Funds `bob` with a large amount for outbidding scenarios.
    function setUp() public {
        config = new HelperConfig();

        // Deploy contracts + mint/approve NFT to seller
        (auction, nft, tokenId) = config.run();

        seller = auction.getSeller();

        // Provide bob with enough ETH to place a very large bid
        vm.deal(bob, MAX_UINT_128);
    }

    // ---------------------------------------------------------
    // START() FUZZ TESTS
    // ---------------------------------------------------------

    /// @notice start() should revert if the caller is not the seller.
    /// @dev
    /// - We constrain `user` to not be zero and not be seller.
    /// - We expect the `YouAreNotSeller` custom error selector.
    function testFuzz__start__revertYouAreNotSeller(address user) public {
        vm.assume(user != ADDRESS_ZERO && user != seller);

        vm.prank(user);
        vm.expectRevert(Auction.Auction__YouAreNotSeller.selector);
        auction.start(ADDRESS_ZERO, ZERO);

        // Auction should remain NOT_STARTED on revert
        assertEq(auction.getAuctionStatus(), STATUS_NOT_STARTED);
    }

    // ---------------------------------------------------------
    // BID() FUZZ TESTS
    // ---------------------------------------------------------

    /// @notice bid() should revert if the auction has not been started.
    /// @dev
    /// - We fund the bidder with exactly `bid`.
    /// - We expect the `AuctionNotStarted` custom error selector.
    function testFuzz__bid__revertAuctionNotStarted(address user, uint256 bid) public {
        vm.assume(user != ADDRESS_ZERO && user != seller);

        // Ensure bid is at least 1 wei and within uint256 range
        bid = bound(bid, 1, type(uint256).max);

        vm.deal(user, bid);

        vm.prank(user);
        vm.expectRevert(Auction.Auction__AuctionNotStarted.selector);
        auction.bid{value: bid}();

        // No refunds should exist because no bid was accepted
        assertEq(auction.getPendingReturnsByUser(user), ZERO);

        // State should still be empty
        Auction.AuctionInformation memory auctionInformation = auction.getAuction();
        assertEq(auctionInformation.highestBid, ZERO);
        assertEq(auctionInformation.highestBidder, ADDRESS_ZERO);
    }

    /// @notice bid() should revert if bid <= current highest bid.
    /// @dev
    /// - Starts the auction via modifier.
    /// - Bob places a huge bid first, becoming highest bidder.
    /// - Fuzzed user then attempts to bid less than that and must revert.
    function testFuzz__bid__revertBidNeedBeHigherThanCurrentHighestBid(address user, uint256 bid)
        public
        startAuction
    {
        vm.assume(user != ADDRESS_ZERO && user != seller);

        // Force the bid to be strictly less than bob's MAX_UINT_128 bid
        bid = bound(bid, 1, type(uint128).max - 1);

        vm.deal(user, bid);

        // Bob sets the current highest bid
        vm.prank(bob);
        auction.bid{value: MAX_UINT_128}();

        // User tries to bid lower than highestBid -> should revert
        vm.prank(user);
        vm.expectRevert(Auction.Auction__BidNeedBeHigherThanCurrentHighestBid.selector);
        auction.bid{value: bid}();

        // User never became highest bidder, so no pending returns for them
        assertEq(auction.getPendingReturnsByUser(user), ZERO);

        // Auction state should still reflect bob as the leader
        Auction.AuctionInformation memory auctionInformation = auction.getAuction();
        assertEq(auctionInformation.highestBid, MAX_UINT_128);
        assertEq(auctionInformation.highestBidder, bob);
    }

    /// @notice bid() should revert if the auction time has ended.
    /// @dev
    /// - Starts the auction via modifier.
    /// - Warps time beyond endAt.
    /// - Any new bid must revert with `AuctionTimeEnded`.
    function testFuzz__bid__revertAuctionTimeEnded(address user, uint256 bid) public startAuction {
        vm.assume(user != ADDRESS_ZERO && user != seller);

        bid = bound(bid, 1, type(uint256).max);
        vm.deal(user, bid);

        // Move forward in time to ensure auction is expired
        vm.warp(block.timestamp + auction.getDuration() + 1);

        vm.prank(user);
        vm.expectRevert(Auction.Auction__AuctionTimeEnded.selector);
        auction.bid{value: bid}();

        // No changes expected
        assertEq(auction.getPendingReturnsByUser(user), ZERO);

        Auction.AuctionInformation memory auctionInformation = auction.getAuction();
        assertEq(auctionInformation.highestBid, ZERO);
        assertEq(auctionInformation.highestBidder, ADDRESS_ZERO);
    }

    /// @notice Successful bid path: user becomes highest bidder with their bid amount.
    /// @dev
    /// - Starts the auction via modifier.
    /// - Funds user and places a bid.
    /// - Asserts state matches expected leader and amount.
    function testFuzz__bid(address user, uint256 bid) public startAuction {
        vm.assume(user != ADDRESS_ZERO && user != seller);

        bid = bound(bid, 1, type(uint256).max);
        vm.deal(user, bid);

        vm.prank(user);
        auction.bid{value: bid}();

        Auction.AuctionInformation memory auctionInformation = auction.getAuction();
        assertEq(auctionInformation.highestBidder, user);
        assertEq(auctionInformation.highestBid, bid);
    }
}
